- name:  install application
  hosts: ec2_app
  become: yes
  tasks:
    - name: execute 'ls'
      command: ls
    - name: install updates
      apt: update_cache=yes
    
    - name: Install required system packages
      apt:
        state: present
        name:
            - ca-certificates
            - curl
            - python3-pip
            - virtualenv
            - python3-setuptools
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: Add Docker Repository
      apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present

    - name: Update apt and install docker-ce
      apt:
          name: docker-ce
          state: latest
          update_cache: true
    
    - name: Install AWS CLI
      apt:
        name: aws-cli
        state: present

    - name: Authenticate Docker to ECR
      shell: "{{ lookup('env', 'AWS_ACCESS_KEY_ID={0} AWS_SECRET_ACCESS_KEY={1} aws ecr get-login-password --region {2}') | awk '{print $1, $3}' }}"
      register: ecr_auth
      environment:
        AWS_ACCESS_KEY_ID: "{{ your_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ your_aws_secret_key }}"
        AWS_DEFAULT_REGION: "eu-central-1"
      changed_when: false

    - name: Run Docker login command
      shell: "{{ ecr_auth.stdout }}"
      when: ecr_auth is succeeded

    - name: start app  
      command: 
        cmd: 'docker run --name app -e DB_USER="admin" -e DB_PASS="admin" -e DB_HOST={{DB_IP}} -p 4000:4000 990162768441.dkr.ecr.eu-central-1.amazonaws.com/mk-repository:app'
  