- name:  install application
  hosts: ec2_app
  become: yes
  tasks:
    - name: execute 'ls'
      command: ls
    - name: install updates
      yum: update_cache=yes
    
    - name: Install required system packages
      yum:
        state: present
        name:
            - ca-certificates
            - collectd-curl
            - python3-pip
            - virtualenv
            - python3-setuptools
        update_cache: true
    - name: Yum repolist for Docker
      yum_repository:
        name: docker
        description: yum repository for docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

    - name: Package Installer For Docker
      package:
        name: docker-ce-3:18.09.1-3.el7
        state: present

    - name: Package Installer For Python3 
      package:
        name: python3
        state: present     

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Configure AWS CLI with Access Key
      command: >
                aws configure set aws_access_key_id "{{ AWS_ACCESS_KEY_ID }}"
                && aws configure set aws_secret_access_key "{{ AWS_SECRET_ACCESS_KEY }}"
                && aws configure set default.region "{{ eu-central-1 }}"
      when: ansible_os_family == 'Debian'  # Adjust based on the OS family of your hosts               

    - name: Log into AWS account
      command: aws sts get-caller-identity
      register: aws_login_output
      when: ansible_os_family == 'Debian'  # Adjust based on the OS family of your hosts   
            
        
    - name: Log in to Amazon ECR
      shell: "$(aws ecr get-login --region eu-central-1)"

    - name: start app  
      command: 
        cmd: 'docker run --name app -e DB_USER="admin" -e DB_PASS="admin" -e DB_HOST={{ DB_IP }} -p 4000:4000 990162768441.dkr.ecr.eu-central-1.amazonaws.com/mk-repository:app'
  