- name:  install application
  hosts: ec2_app
  become: yes
  tasks:
    - name: execute 'ls'
      command: ls
    - name: install updates
      apt: update_cache=yes
    
    - name: Install required system packages
      apt:
        state: present
        name:
            - ca-certificates
            - curl
            - python3-pip
            - virtualenv
            - python3-setuptools
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: Add Docker Repository
      apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present

    - name: Update apt and install docker-ce
      apt:
          name: docker-ce
          state: latest
          update_cache: true
    
    - name:
      command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip && unzip awscliv2.zip  && sudo ./aws/install"
                
               

    - name: Configure AWS CLI with Access Key
      command: >
                aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                && aws configure set default.region "eu-central-1"

    - name: Log into AWS account
      command: aws sts get-caller-identity
      register: aws_login_output
            
        
    - name: Log in to Amazon ECR
      shell: "$(aws ecr get-login --region eu-central-1)"

    - name: start app  
      command: 
        cmd: 'docker run --name app -e DB_USER="admin" -e DB_PASS="admin" -e DB_HOST={{DB_IP}} -p 4000:4000 990162768441.dkr.ecr.eu-central-1.amazonaws.com/mk-repository:app'
  