- name:  install database
  hosts: ec2_db
  become: yes
  tasks:
    - name: execute 'ls'
      command: ls
    
    - name: install updates
      ansible.builtin.dnf: update_cache=yes
    
    - name: Install required system packages
      ansible.builtin.dnf:
        state: present
        name:
            - ca-certificates
            - collectd-curl
            - python3-pip
            - virtualenv
            - python3-setuptools
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: Add Docker Repository
      apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present

    - name: Update apt and install docker-ce
      apt:
          name: docker-ce
          state: latest
          update_cache: true
    - name: Install AWS CLI
      apt:
            name: awscli
            state: present
      when: ansible_os_family == 'Debian'  # Adjust based on the OS family of your hosts    

    - name: Configure AWS CLI with Access Key
      command: >
                aws configure set aws_access_key_id "{{ AWS_ACCESS_KEY_ID }}"
                && aws configure set aws_secret_access_key "{{ AWS_SECRET_ACCESS_KEY }}"
                && aws configure set default.region "{{ eu-central-1 }}"
      when: ansible_os_family == 'Debian'  # Adjust based on the OS family of your hosts               

    - name: Log into AWS account
      command: aws sts get-caller-identity
      register: aws_login_output
      when: ansible_os_family == 'Debian'   
            
    - name: Log in to Amazon ECR
      shell: "$(aws ecr get-login --region eu-central-1)"

    - name: start db  
      command: 
        cmd: "docker run -p 5432:5432 990162768441.dkr.ecr.eu-central-1.amazonaws.com/mk-repository:db-custom"
  